# -*- coding: utf-8 -*-
"""Another copy of ridewise_infosys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOUG62bOi6JHvnqw1otLb55nBk9vatfp
"""

import pandas as pd

hour = pd.read_csv("hour.csv")
day = pd.read_csv("day.csv")

hour.head()

hour.info()

hour.describe()

hour.isnull().sum()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(hour.groupby("hr")["cnt"].mean())
plt.xlabel("Hour")
plt.ylabel("Average Rentals")
plt.title("Average bike rentals by hour")
plt.show()

plt.figure(figsize=(8,5))
plt.bar(hour["season"].unique(), hour.groupby("season")["cnt"].mean())
plt.xlabel("Season")
plt.ylabel("Average Rentals")
plt.title("Rentals by Season")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

hour = pd.read_csv("hour.csv")

plt.figure(figsize=(7,5))
plt.hist(hour["cnt"], bins=30)
plt.title("Distribution of Total Bike Rentals")
plt.xlabel("Bike Rentals")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(7,5))
sns.barplot(x="season", y="cnt", data=hour, estimator="mean")
plt.title("Average Bike Rentals per Season")
plt.show()

plt.figure(figsize=(10,5))
sns.lineplot(x="mnth", y="cnt", data=hour)
plt.title("Rentals by Month")
plt.show()

plt.figure(figsize=(10,5))
sns.lineplot(x="hr", y="cnt", data=hour)
plt.title("Average Rentals by Hour")
plt.show()

plt.figure(figsize=(6,5))
sns.barplot(x="workingday", y="cnt", data=hour, estimator="mean")
plt.title("Rentals: Working Day vs Non-Working Day")
plt.show()

plt.figure(figsize=(7,5))
sns.barplot(x="weathersit", y="cnt", data=hour, estimator="mean")
plt.title("Rentals by Weather Condition")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(x="temp", y="cnt", data=hour)
plt.title("Temperature vs Bike Rentals")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(x="hum", y="cnt", data=hour)
plt.title("Humidity vs Rentals")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(x="windspeed", y="cnt", data=hour)
plt.title("Windspeed vs Rentals")
plt.show()

plt.figure(figsize=(12,7))

numeric_df = hour.select_dtypes(include=["number"])   # keep only number columns

sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()



plt.figure(figsize=(7,5))
sns.barplot(x="yr", y="cnt", data=hour, estimator="mean")
plt.title("Rentals by Year")
plt.show()

