# -*- coding: utf-8 -*-
"""sahana_model_Training_25/12/25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TolCNMKRMTrguNhPnt-LQyJEU13s6jr9
"""

!pip install xgboost lightgbm

import pandas as pd

hour = pd.read_csv("hour.csv")
hour.head()

hour = hour.drop(['casual', 'registered'], axis=1)

hour = hour.drop(['instant', 'dteday'], axis=1)

hour.columns

X = hour.drop('cnt', axis=1)
y = hour['cnt']

# Train-Test Split (Standard & Safe)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score
import pandas as pd

#Define all models
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "SVR": SVR(),
    "XGBoost": XGBRegressor(
        n_estimators=100,
        learning_rate=0.1,
        random_state=42,
        verbosity=0
    ),
    "LightGBM": LGBMRegressor(
        n_estimators=100,
        learning_rate=0.1,
        random_state=42
    )
}

#Train, predict, evaluate (MAIN PART)
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    r2 = r2_score(y_test, predictions)
    results.append([name, r2])

#Show results as a table
results_df = pd.DataFrame(results, columns=["Model", "R2 Score"])
results_df = results_df.sort_values(by="R2 Score", ascending=False)
results_df

final_model = LGBMRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

final_model.fit(X_train, y_train)

final_predictions = final_model.predict(X_test)
final_r2 = r2_score(y_test, final_predictions)

final_r2

import pandas as pd

day_df = pd.read_csv("day.csv")
day_df.head()

# Target
y_day = day_df["cnt"]

# Drop leakage and identifiers
X_day = day_df.drop(
    columns=["cnt", "casual", "registered", "instant", "dteday"]
)

#Train–Test Split
from sklearn.model_selection import train_test_split

X_day_train, X_day_test, y_day_train, y_day_test = train_test_split(
    X_day, y_day, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor

day_models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(
        n_estimators=100, random_state=42
    ),
    "LightGBM": LGBMRegressor(
        n_estimators=100,
        learning_rate=0.1,
        random_state=42
    )
}

#Train, Predict, Evaluate (MAIN PART)
from sklearn.metrics import r2_score

day_results = []

for name, model in day_models.items():
    model.fit(X_day_train, y_day_train)
    preds = model.predict(X_day_test)
    r2 = r2_score(y_day_test, preds)
    day_results.append([name, r2])

#Results Table
day_results_df = pd.DataFrame(
    day_results, columns=["Model", "R2 Score"]
).sort_values(by="R2 Score", ascending=False)

day_results_df

#Final Daily Model
final_day_model = LGBMRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

final_day_model.fit(X_day_train, y_day_train)

day_preds = final_day_model.predict(X_day_test)
final_day_r2 = r2_score(y_day_test, day_preds)

final_day_r2

# Step 10: Visualize Results
import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style
sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.barplot(x="R2 Score", y="Model", data=results_df, palette="viridis")
plt.title("Model Comparison based on R² Score", fontsize=16)
plt.xlabel("R² Score", fontsize=14)
plt.ylabel("Model", fontsize=14)
plt.xlim(0,1)  # R² score ranges from 0 to 1
plt.show()

#Hourly Graph

#We can plot average bike counts per hour to show how usage changes throughout the day.

import matplotlib.pyplot as plt
import seaborn as sns

# Hourly graph
plt.figure(figsize=(12,6))
hourly_data = hour.groupby('hr')['cnt'].mean().reset_index()  # Average counts per hour
sns.lineplot(x='hr', y='cnt', data=hourly_data, marker='o', color='blue')
plt.title("Average Bike Count by Hour of the Day", fontsize=16)
plt.xlabel("Hour", fontsize=14)
plt.ylabel("Average Count", fontsize=14)
plt.xticks(range(0,24))
plt.grid(True)
plt.show()

# -----------------------------
# Step 1: Imports
# -----------------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

sns.set(style="whitegrid")

# -----------------------------
# Step 2: Load Dataset
# -----------------------------
hour_raw = pd.read_csv("hour.csv")  # keep raw copy for plotting
hour = hour_raw.copy()

# -----------------------------
# Step 3: Split Features & Target
# -----------------------------
X = hour.drop(['instant','dteday','cnt'], axis=1)
y = hour['cnt']

# -----------------------------
# Step 4: Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------
# Step 5: Preprocessing
# -----------------------------
cat_cols = X.select_dtypes(include='object').columns.tolist()
num_cols = X.select_dtypes(exclude='object').columns.tolist()

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
    ('num', 'passthrough', num_cols)
])

# -----------------------------
# Step 6: Define Models
# -----------------------------
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "SVR": SVR(),
    "XGBoost": XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42, verbosity=0),
    "LightGBM": LGBMRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
}

# -----------------------------
# Step 7: Train Models & Predict
# -----------------------------
predictions_dict = {}
results = []

for name, model in models.items():
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('model', model)
    ])
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)
    predictions_dict[name] = preds
    r2 = r2_score(y_test, preds)
    results.append([name, r2])

# -----------------------------
# Step 8: Show R2 Score Table
# -----------------------------
results_df = pd.DataFrame(results, columns=["Model", "R2 Score"])
results_df = results_df.sort_values(by="R2 Score", ascending=False)
print(results_df)

# -----------------------------
# Step 9: Prepare Data for Plotting
# -----------------------------
X_test_reset = X_test.reset_index(drop=True)
y_test_reset = y_test.reset_index(drop=True)

# Include actual, hr, dteday
plot_data = X_test_reset.copy()
plot_data['Actual'] = y_test_reset
plot_data['hr'] = hour_raw.loc[X_test.index, 'hr']
plot_data['dteday'] = pd.to_datetime(hour_raw.loc[X_test.index, 'dteday'])

for model_name, preds in predictions_dict.items():
    plot_data[model_name] = preds

# -----------------------------
# Step 10: Hourly Graph
# -----------------------------
plt.figure(figsize=(14,6))
hourly_avg = plot_data.groupby('hr')[['Actual'] + list(models.keys())].mean().reset_index()

for model_name in models.keys():
    plt.plot(hourly_avg['hr'], hourly_avg[model_name], marker='o', label=model_name)

plt.plot(hourly_avg['hr'], hourly_avg['Actual'], marker='o', color='black', linewidth=2, label='Actual')
plt.title("Hourly Bike Count: Model Predictions vs Actual", fontsize=16)
plt.xlabel("Hour", fontsize=14)
plt.ylabel("Average Count", fontsize=14)
plt.xticks(range(0,24))
plt.legend()
plt.grid(True)
plt.show()

# -----------------------------
# Step 11: Daily Graph
# -----------------------------
plt.figure(figsize=(16,6))
daily_avg = plot_data.groupby('dteday')[['Actual'] + list(models.keys())].mean().reset_index()

for model_name in models.keys():
    plt.plot(daily_avg['dteday'], daily_avg[model_name], label=model_name)

plt.plot(daily_avg['dteday'], daily_avg['Actual'], color='black', linewidth=2, label='Actual')
plt.title("Daily Bike Count: Model Predictions vs Actual", fontsize=16)
plt.xlabel("Date", fontsize=14)
plt.ylabel("Total Count", fontsize=14)
plt.legend()
plt.grid(True)
plt.show()

# Dictionary to store predictions for each model
predictions_dict = {}

for name, model in models.items():
    pipe = Pipeline([
        ('preprocess', preprocessor),
        ('model', model)
    ])
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)
    predictions_dict[name] = preds

# Add actual counts for comparison
X_test_reset = X_test.reset_index(drop=True)
y_test_reset = y_test.reset_index(drop=True)
X_test_reset['Actual'] = y_test_reset

# If 'hr' and 'dteday' were dropped before, keep them in X_test for plotting
# Assuming 'hr' is hour and 'dteday' is date
X_test_reset['hr'] = hour.loc[X_test_reset.index, 'hr']
X_test_reset['dteday'] = hour.loc[X_test_reset.index, 'dteday']

# Create a dataframe for plotting
plot_data = X_test_reset.copy()
for model_name, preds in predictions_dict.items():
    plot_data[model_name] = preds

plt.figure(figsize=(14,6))

hourly_avg = plot_data.groupby('hr')[['Actual'] + list(models.keys())].mean().reset_index()

for model_name in models.keys():
    plt.plot(hourly_avg['hr'], hourly_avg[model_name], marker='o', label=model_name)

plt.plot(hourly_avg['hr'], hourly_avg['Actual'], marker='o', color='black', linewidth=2, label='Actual')
plt.title("Hourly Bike Count: Model Predictions vs Actual", fontsize=16)
plt.xlabel("Hour", fontsize=14)
plt.ylabel("Average Count", fontsize=14)
plt.xticks(range(0,24))
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(16,6))

daily_avg = plot_data.groupby('dteday')[['Actual'] + list(models.keys())].mean().reset_index()

for model_name in models.keys():
    plt.plot(daily_avg['dteday'], daily_avg[model_name], label=model_name)

plt.plot(daily_avg['dteday'], daily_avg['Actual'], color='black', linewidth=2, label='Actual')
plt.title("Daily Bike Count: Model Predictions vs Actual", fontsize=16)
plt.xlabel("Date", fontsize=14)
plt.ylabel("Total Count", fontsize=14)
plt.legend()
plt.grid(True)
plt.show()

