# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HONcHs_7GPODkx3pydU-jfyygWyrx48
"""

import pandas as pd

hour = pd.read_csv("hour.csv")
hour.head()

# 1️⃣ Basic Feature: is_weekend
hour['is_weekend'] = hour['weekday'].apply(lambda x: 1 if x in [0,6] else 0)

# Check
hour[['weekday','is_weekend']].head(10)

def time_of_day(hr):
    if 5 <= hr < 12:
        return 'Morning'
    elif 12 <= hr < 17:
        return 'Afternoon'
    elif 17 <= hr < 21:
        return 'Evening'
    else:
        return 'Night'

hour['time_of_day'] = hour['hr'].apply(time_of_day)

# Check first 10 rows
hour[['hr','time_of_day']].head(10)

# Basic Feature: is_peak_hour
hour['is_peak_hour'] = hour['hr'].apply(lambda x: 1 if x in [7,8,9,17,18,19] else 0)

# Check first 10 rows
hour[['hr','is_peak_hour']].head(10)

# Intermediate Feature: demand_level
hour['demand_level'] = pd.cut(
    hour['cnt'],
    bins=[-1, 100, 300, hour['cnt'].max()],
    labels=['Low','Medium','High']
)

# Check first 10 rows
hour[['cnt','demand_level']].head(10)

hour['weather_quality'] = hour['weathersit'].map({
    1: 'Good',
    2: 'Moderate',
    3: 'Bad',
    4: 'Very Bad'
})

# Check first 10 rows
hour[['weathersit','weather_quality']].head(10)

# Advanced Feature: comfort_score
# Formula: higher temp, lower humidity, lower wind = more comfortable
hour['comfort_score'] = hour['temp'] * (1 - hour['hum']) * (1 - hour['windspeed'])

# Check first 10 rows
hour[['temp','hum','windspeed','comfort_score']].head(10)

# Advanced Feature: demand_pressure
avg_cnt = hour['cnt'].mean()
hour['demand_pressure'] = hour['cnt'] / avg_cnt

# Check first 10 rows
hour[['cnt','demand_pressure']].head(10)

# Previous hour demand difference
hour['prev_hour_cnt'] = hour['cnt'].shift(1)  # previous hour rentals
hour['demand_change'] = hour['cnt'] - hour['prev_hour_cnt']

hour[['cnt','prev_hour_cnt','demand_change']].head(10)

hour['weekend_peak'] = hour.apply(lambda x: 1 if (x['is_weekend']==1 and x['is_peak_hour']==1) else 0, axis=1)
hour[['is_weekend','is_peak_hour','weekend_peak']].head(10)

def temp_label(row):
    if row['temp'] < 0.3:
        return 'Cold'
    elif row['temp'] < 0.5:
        return 'Cool'
    elif row['temp'] < 0.7:
        return 'Comfortable'
    else:
        return 'Hot'

hour['temp_label'] = hour.apply(temp_label, axis=1)
hour[['temp','hum','temp_label']].head(10)

hour['morning_rush'] = hour['hr'].apply(lambda x: 1 if x in [7,8,9] else 0)
hour['evening_rush'] = hour['hr'].apply(lambda x: 1 if x in [17,18,19] else 0)
hour[['hr','morning_rush','evening_rush']].head(10)

hour['demand_weather_ratio'] = hour['cnt'] / (hour['comfort_score'] + 0.01)  # +0.01 to avoid division by zero
hour[['cnt','comfort_score','demand_weather_ratio']].head(10)

